# Generated by Django 5.0.1 on 2024-02-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условия бронирования')),
            ],
            options={
                'verbose_name': 'Условия бронирования',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular', models.CharField(max_length=10, verbose_name='Единственное число (1 час)')),
                ('plural', models.CharField(max_length=10, verbose_name='Множественное число (2 часа)')),
                ('plural_special', models.CharField(max_length=10, verbose_name='Множественное число дополнительное (30 часов)')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('start_price', models.PositiveIntegerField(verbose_name='Начальная цена')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('booking_conditions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingconditions', verbose_name='Условия бронирования')),
                ('period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='landing.period', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', verbose_name='Фото/Видео')),
                ('miniature', models.FileField(blank=True, null=True, upload_to='media/mini/', verbose_name='Миниатюра (опционально)')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='landing_att_content_59ff28_idx')],
            },
        ),
    ]
