# Generated by Django 5.0.1 on 2024-02-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_attachment_file_alter_attachment_miniature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['order'], 'verbose_name': 'Фото/Видео', 'verbose_name_plural': 'Фото/Видео'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['order'], 'verbose_name': 'Домик', 'verbose_name_plural': 'Домики'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='house',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
