# Generated by Django 5.0.1 on 2024-02-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_attachment_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingconditions',
            name='description',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем больше число, тем позже эл-т будет отображаться в списке', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем больше число, тем позже эл-т будет отображаться в списке', verbose_name='Порядок отображения'),
        ),
        migrations.CreateModel(
            name='BookingConditionsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Пункт')),
                ('booking_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.bookingconditions')),
            ],
        ),
    ]
