# Generated by Django 5.0.1 on 2024-02-08 19:34

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_wellnesstreatment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingConditions',
            new_name='AdditionalInfo',
        ),
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='miniature',
            field=models.FileField(blank=True, help_text='Изображение, чье разрешение должно быть приближено к 420х300, но не меньше. Опционально, но так сайт будет грузиться быстрее', null=True, upload_to=landing.models.Attachment.get_miniature_upload_path, verbose_name='Миниатюра (опционально)'),
        ),
    ]
