# Generated by Django 5.0.1 on 2024-02-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_rename_bookingconditions_additionalinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.additionalinfo')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительная информация',
            },
        ),
        migrations.DeleteModel(
            name='BookingConditionsItem',
        ),
    ]
