# Generated by Django 5.0.1 on 2024-02-08 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_additionalinfoitem_delete_bookingconditionsitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfoitem',
            options={'verbose_name': 'Пункт', 'verbose_name_plural': 'Пункты'},
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('start_price', models.PositiveIntegerField(verbose_name='Начальная цена')),
                ('duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем позже эл-т будет отображаться в списке', verbose_name='Порядок отображения')),
                ('booking_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.additionalinfo', verbose_name='Условия бронирования')),
                ('period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='landing.period', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Досуг',
                'verbose_name_plural': 'Досуг',
                'ordering': ['order'],
            },
        ),
    ]
