# Generated by Django 5.0.1 on 2024-02-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_additionalinfoitem_options_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='booking_conditions',
        ),
        migrations.RemoveField(
            model_name='house',
            name='booking_conditions',
        ),
        migrations.RemoveField(
            model_name='wellnesstreatment',
            name='booking_conditions',
        ),
        migrations.AddField(
            model_name='action',
            name='additional_info',
            field=models.ForeignKey(blank=True, help_text='Добавляется в конец описания и открывается отдельном окном при нажатии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.additionalinfo', verbose_name='Доп. информация'),
        ),
        migrations.AddField(
            model_name='house',
            name='additional_info',
            field=models.ForeignKey(blank=True, help_text='Добавляется в конец описания и открывается отдельном окном при нажатии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.additionalinfo', verbose_name='Доп. информация'),
        ),
        migrations.AddField(
            model_name='wellnesstreatment',
            name='additional_info',
            field=models.ForeignKey(blank=True, help_text='Добавляется в конец описания и открывается отдельном окном при нажатии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.additionalinfo', verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wellnesstreatment',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
