# Generated by Django 5.0.1 on 2024-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_remove_action_booking_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='landing/our_products/', verbose_name='Фото/Видео')),
                ('miniature', models.FileField(blank=True, help_text='Изображение, чье разрешение должно быть приближено к 400x400, но не меньше. Опционально, но так сайт будет грузиться быстрее', null=True, upload_to='landing/mini/our_products/', verbose_name='Миниатюра (опционально)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем позже эл-т будет отображаться в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Фото/Видео для "Наша продукция"',
                'verbose_name_plural': 'Фото/Видео для "Наша продукция"',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='start_price',
            field=models.PositiveIntegerField(help_text='Оставьте 0 если это бесплатно', verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='displayed_name',
            field=models.CharField(default='Доп. информация', help_text='Название, которое будет отображаться на сайте', max_length=100, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='inner_name',
            field=models.CharField(default='Доп. информация', help_text='Это название уже для вашего удобства, оно отображается здесь, в админке', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='house',
            name='start_price',
            field=models.PositiveIntegerField(help_text='Оставьте 0 если это бесплатно', verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='period',
            name='plural',
            field=models.CharField(max_length=6, verbose_name='Множественное число (2 часа)'),
        ),
        migrations.AlterField(
            model_name='period',
            name='plural_special',
            field=models.CharField(max_length=6, verbose_name='Множественное число дополнительное (30 часов)'),
        ),
        migrations.AlterField(
            model_name='period',
            name='singular',
            field=models.CharField(max_length=6, verbose_name='Единственное число (1 час)'),
        ),
        migrations.AlterField(
            model_name='wellnesstreatment',
            name='start_price',
            field=models.PositiveIntegerField(help_text='Оставьте 0 если это бесплатно', verbose_name='Начальная цена'),
        ),
    ]
