# Generated by Django 5.0.1 on 2024-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_news_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Досуг', 'verbose_name_plural': 'Досуг'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Фото/Видео', 'verbose_name_plural': 'Фото/Видео'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Домик', 'verbose_name_plural': 'Домики'},
        ),
        migrations.AlterModelOptions(
            name='ourproduct',
            options={'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterModelOptions(
            name='wellnesstreatment',
            options={'verbose_name': 'Оздоровительная процедура', 'verbose_name_plural': 'Оздоровительные процедуры'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='order',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='house',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ourproduct',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ourproduct',
            name='miniature',
        ),
        migrations.RemoveField(
            model_name='ourproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wellnesstreatment',
            name='order',
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(blank=True, choices=[('кг', 'килограмм'), ('шт', 'штука'), ('л', 'литр'), ('г', 'грамм')], max_length=4, null=True, verbose_name='Ед. измерения'),
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
