# Generated by Django 5.0.1 on 2024-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_alter_action_options_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
