# Generated by Django 5.0.1 on 2024-02-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_drop_ourproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('measure', models.CharField(blank=True, choices=[('кг', 'килограмм'), ('шт', 'штука'), ('л', 'литр'), ('г', 'грамм')], max_length=4, null=True, verbose_name='Ед. измерения')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
