# Generated by Django 5.0.1 on 2024-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_ourproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourproduct',
            options={'ordering': ['-is_available', 'price'], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AddField(
            model_name='action',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='house',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='wellnesstreatment',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('г', 'грамм'), ('шт', 'штука'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
