# Generated by Django 5.0.1 on 2024-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_alter_ourproduct_options_action_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='order',
        ),
        migrations.AlterField(
            model_name='house',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='house',
            name='start_price',
            field=models.PositiveIntegerField(help_text='Поставьте 0 если это бесплатно', verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
