# Generated by Django 5.0.1 on 2024-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_remove_attachment_order_alter_house_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['order'], 'verbose_name': 'Фото/Видео', 'verbose_name_plural': 'Фото/Видео'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('г', 'грамм'), ('шт', 'штука'), ('л', 'литр'), ('кг', 'килограмм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
