# Generated by Django 5.0.1 on 2024-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_alter_action_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproduct',
            name='order',
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('л', 'литр'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
