# Generated by Django 5.0.1 on 2024-02-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_bookingitem_alter_ourproduct_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='booking_identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingitem', verbose_name='Идентификатор бронируемого объекта'),
        ),
        migrations.AddField(
            model_name='house',
            name='booking_identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingitem', verbose_name='Идентификатор бронируемого объекта'),
        ),
        migrations.AddField(
            model_name='wellnesstreatment',
            name='booking_identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingitem', verbose_name='Идентификатор бронируемого объекта'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('г', 'грамм'), ('л', 'литр'), ('кг', 'килограмм'), ('шт', 'штука')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
