# Generated by Django 5.0.1 on 2024-03-04 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_action_booking_identifier_house_booking_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Период/Кол-во', 'verbose_name_plural': 'Периоды/Кол-во'},
        ),
        migrations.AlterField(
            model_name='action',
            name='booking_identifier',
            field=models.ForeignKey(blank=True, help_text='Нужен для системы бронирования. Если пустой, то забронировать данный эл-т будет нельзя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingitem', verbose_name='Идентификатор бронируемого объекта'),
        ),
        migrations.AlterField(
            model_name='action',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='landing.period', verbose_name='Период/Кол-во'),
        ),
        migrations.AlterField(
            model_name='house',
            name='booking_identifier',
            field=models.ForeignKey(blank=True, help_text='Нужен для системы бронирования. Если пустой, то забронировать данный эл-т будет нельзя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingitem', verbose_name='Идентификатор бронируемого объекта'),
        ),
        migrations.AlterField(
            model_name='house',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='landing.period', verbose_name='Период/Кол-во'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('шт', 'штука'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='wellnesstreatment',
            name='booking_identifier',
            field=models.ForeignKey(blank=True, help_text='Нужен для системы бронирования. Если пустой, то забронировать данный эл-т будет нельзя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.bookingitem', verbose_name='Идентификатор бронируемого объекта'),
        ),
        migrations.AlterField(
            model_name='wellnesstreatment',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='landing.period', verbose_name='Период/Кол-во'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(editable=False, max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(editable=False, max_length=20, verbose_name='Номер телефона')),
                ('adults_count', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во взрослых')),
                ('childs_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Кол-во детей')),
                ('booking_date', models.DateTimeField(editable=False, verbose_name='Дата бронирования и время бронирования')),
                ('is_has_whatsapp', models.BooleanField(editable=False, verbose_name='Имеется Whatsapp')),
                ('status', models.CharField(choices=[('Активно', 'Активно'), ('Одобрено', 'Одобрено'), ('Отменено', 'Отменено')], default='Активно', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('booking_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='landing.bookingitem', verbose_name='Что забронировано')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'ordering': ['booking_date'],
            },
        ),
    ]
