# Generated by Django 5.0.1 on 2024-03-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_alter_period_options_alter_action_booking_identifier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingItem',
            new_name='BookingIdentifier',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_item',
            new_name='booking_identifier',
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
