# Generated by Django 5.0.1 on 2024-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_rename_bookingitem_bookingidentifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Заявка на бронирование', 'verbose_name_plural': 'Заявки на бронирование'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Бронирование по'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('г', 'грамм'), ('кг', 'килограмм'), ('шт', 'штука'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
