# Generated by Django 5.0.1 on 2024-03-05 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_alter_ourproduct_measure_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('г', 'грамм'), ('кг', 'килограмм'), ('шт', 'штука')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(editable=False, max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(editable=False, max_length=20, verbose_name='Номер телефона')),
                ('adults_count', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во взрослых')),
                ('childs_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Кол-во детей')),
                ('start_date', models.DateTimeField(editable=False, verbose_name='Бронирование с')),
                ('end_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Бронирование по')),
                ('is_has_whatsapp', models.BooleanField(editable=False, verbose_name='Имеется Whatsapp')),
                ('status', models.CharField(choices=[('Активно', 'Активно'), ('Одобрено', 'Одобрено'), ('Отменено', 'Отменено')], default='Активно', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('booking_identifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='landing.bookingidentifier', verbose_name='Что забронировано')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'ordering': ['start_date'],
            },
        ),
    ]
