# Generated by Django 5.0.1 on 2024-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_alter_ourproduct_measure_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('шт', 'штука'), ('г', 'грамм'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
