# Generated by Django 5.0.1 on 2024-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_booking_date_end_fact_booking_date_start_fact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя питомаца')),
                ('desription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фотографии для ',
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['status', '-date_create'], 'verbose_name': 'Заявка на бронирование', 'verbose_name_plural': 'Заявки на бронирование'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='desired_dates',
            field=models.CharField(editable=False, max_length=400, verbose_name='Желаемые даты'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='manager_comment',
            field=models.TextField(blank=True, help_text='Если надо что-то пометить для себя', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
