# Generated by Django 5.0.1 on 2024-03-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_alter_ourpet_options_ourpet_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourpet',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('г', 'грамм'), ('л', 'литр'), ('шт', 'штука')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
