# Generated by Django 5.0.1 on 2024-03-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0038_rename_desription_ourpet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_dayly',
            field=models.BooleanField(default=False, verbose_name='Суточное бронирование'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end_fact',
            field=models.DateTimeField(blank=True, help_text='Если это посуточное бронирование, то указывайте здесь, пожалуйста, последний полный день, чтобы система бронирования следующий день помечала как свободный', null=True, verbose_name='Последний полный день бронирования/Дата окончания бронирования'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('шт', 'штука'), ('л', 'литр'), ('кг', 'килограмм'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
