# Generated by Django 5.0.1 on 2024-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_booking_is_late_checkout_alter_booking_date_end_fact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='booking_btn_text',
            field=models.CharField(choices=[('Забронировать', 'Забронировать'), ('Записаться', 'Записаться')], default='Забронировать', max_length=25, verbose_name='Текст кнопки в карточке'),
        ),
        migrations.AddField(
            model_name='house',
            name='booking_btn_text',
            field=models.CharField(choices=[('Забронировать', 'Забронировать'), ('Записаться', 'Записаться')], default='Забронировать', max_length=25, verbose_name='Текст кнопки в карточке'),
        ),
        migrations.AddField(
            model_name='wellnesstreatment',
            name='booking_btn_text',
            field=models.CharField(choices=[('Забронировать', 'Забронировать'), ('Записаться', 'Записаться')], default='Забронировать', max_length=25, verbose_name='Текст кнопки в карточке'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end_fact',
            field=models.DateTimeField(blank=True, help_text='При поздном выезде другие люди не смогут забронировать последнюю дату', null=True, verbose_name='Дата окончания бронирования'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('г', 'грамм'), ('шт', 'штука'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
