# Generated by Django 5.0.1 on 2024-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0041_action_booking_btn_text_house_booking_btn_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_late_checkout',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Поздний выезд'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('шт', 'штука'), ('кг', 'килограмм'), ('г', 'грамм'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
