# Generated by Django 5.0.1 on 2024-03-25 20:02

import image_cropping.fields
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_alter_booking_is_late_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to=landing.models.Attachment.get_upload_path, verbose_name='Фото/Видео'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='miniature',
            field=image_cropping.fields.ImageRatioField('file', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('шт', 'штука'), ('кг', 'килограмм'), ('л', 'литр'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
