# Generated by Django 5.0.1 on 2024-03-28 18:19

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0045_alter_attachment_file_alter_attachment_miniature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='miniature',
            field=image_cropping.fields.ImageRatioField('file', '420x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('л', 'литр'), ('г', 'грамм'), ('шт', 'штука')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
