# Generated by Django 5.0.1 on 2024-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0046_alter_attachment_miniature_alter_ourproduct_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_early_checkin',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Ранний заезд'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('л', 'литр'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
