# Generated by Django 5.0.1 on 2024-04-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0047_booking_is_early_checkin_alter_ourproduct_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_comment',
            field=models.TextField(blank=True, help_text='Из заявки на бронирование', null=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end_fact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Факт. конец'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_start_fact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Факт. начало'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_early_checkin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ранний заезд'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_late_checkout',
            field=models.BooleanField(blank=True, default=False, verbose_name='Поздний выезд'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('a', 'Активно 🟢'), ('b', 'Бронь ✔️'), ('c', 'Отменено ❌')], default='a', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('кг', 'килограмм'), ('г', 'грамм'), ('шт', 'штука'), ('л', 'литр')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
