# Generated by Django 5.0.1 on 2024-04-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0048_booking_user_comment_alter_booking_date_end_fact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_comment',
            field=models.TextField(blank=True, editable=False, help_text='Из заявки на бронирование', null=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
