# Generated by Django 5.0.1 on 2024-04-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0049_alter_booking_user_comment_alter_ourproduct_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=500, verbose_name='Сообщение об ошибке')),
                ('stack_trace', models.TextField(verbose_name='Трассировка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
        ),
    ]
