# Generated by Django 5.0.1 on 2024-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0051_alter_errorlog_options_alter_errorlog_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='error_message',
            field=models.CharField(max_length=500, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('г', 'грамм'), ('шт', 'штука')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
