# Generated by Django 5.0.1 on 2024-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0052_alter_errorlog_error_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['is_solved', '-date'], 'verbose_name': 'Ошибка', 'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AddField(
            model_name='errorlog',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='additional_info',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='error_message',
            field=models.CharField(editable=False, max_length=500, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='stack_trace',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Трассировка'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('г', 'грамм'), ('кг', 'килограмм'), ('шт', 'штука')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
